### ISSUE TITLE
Running the example code snippet results in the exception "context deadline exceeded"

### ISSUE THREAD

**Issue by RaheelYawar** [ipfs-shipyard/net-ipfs-http-client#26]
Running the code snippet is causing a timeout and the following exception is displayed. 

```
Unhandled exception. System.Net.Http.HttpRequestException: context deadline exceeded
   at Ipfs.Http.IpfsClient.ThrowOnErrorAsync(HttpResponseMessage response)
   at Ipfs.Http.IpfsClient.PostDownloadAsync(String command, CancellationToken cancel, String arg, String[] options)
   at Ipfs.Http.FileSystemApi.ReadAllTextAsync(String path, CancellationToken cancel)

```

**Comment by Arlodotexe** [comment]
Could you provide more information about what code snippet you ran?
